### ISSUE TITLE
VNNI: Instructions Required Non Haswell Platform

### ISSUE THREAD

**Issue by xe1gyq** [VictorRodriguez/AVX-SG#7]
We are taking this platform:

```sh
processor	: 7
vendor_id	: GenuineIntel
cpu family	: 6
model		: 158
model name	: Intel(R) Core(TM) i7-8809G CPU @ 3.10GHz
stepping	: 9
microcode	: 0xd6
cpu MHz		: 1600.024
```

And executing the build of VNNI container:

```sh
user@skull-01:~/vmrod/AVX-SG$ make vnni
mkdir -p build/
gcc -O3 -march=haswell src/basic_vpmaddwd.c -o build/basic_vpmaddwd
src/basic_vpmaddwd.c: In function ‘foo’:
src/basic_vpmaddwd.c:42:15: warning: implicit declaration of function ‘_mm256_setr_m128i’; did you mean ‘_mm256_setr_epi8’? [-Wimplicit-function-declaration]
  result_temp =_mm256_setr_m128i(result,result);
               ^~~~~~~~~~~~~~~~~
               _mm256_setr_epi8
src/basic_vpmaddwd.c:42:14: error: incompatible types when assigning to type ‘__m256i {aka __vector(4) long long int}’ from type ‘int’
  result_temp =_mm256_setr_m128i(result,result);
              ^
Makefile:41: recipe for target 'vnni' failed
make: *** [vnni] Error 1
```

Any help is highly appreciated...

**Comment by VictorRodriguez** [comment]
What compiler version do you have ? 
It seems that your GCC compiler does not have VNNI intrinsics support
I have tested in Centos 8 and works fine

[centos@simics-test-1 AVX-SG]$ gcc -O3 -march=haswell src/basic_vpmaddwd.c -o build/basic_vpmaddwd
[centos@simics-test-1 AVX-SG]$ gcc --version
gcc (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[centos@simics-test-1 AVX-SG]$

**Comment by VictorRodriguez** [comment]
Is ok if I close this bug? since is related to the compiler version
