### ISSUE TITLE
where the functions definitions?

### ISSUE THREAD

**Issue by chengguosun** [VictorRodriguez/AVX-SG#9]
hello,
I can't find some tile functions definitions, such as "init_tile_config", "init_tile_reg_and_src_with_buffer"..., and "amx-check.h" head file. Where are the function definitions and header files? Thank you very much

**Comment by chengguosun** [comment]
these functions are in the latest GCC, thanks.

**Comment by VictorRodriguez** [comment]
Yes, there is a docker image I put to get the latest GCC, you will also need Binutils latest to see the objdump of the file
